apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.component_name }}
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.component_name }}
  dataFrom:
    - extract:
        key: {{ .Values.component_name }}