 {{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.component_name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.name }}
      secretName: {{ .Values.component_name }}-tls
  rules:
    - host: {{ .Values.ingress.name }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.component_name }}
                port:
                  number: {{ .Values.service.port }}

   {{ end }}
 